services:
  todoapp:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopass
    depends_on:
      - db
  
  db:
    image: postgres:16-alpine
    container_name: psql
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopass
    ports:
      - "5432:5432"