services:
  todoapp:
    build: .
    ports:
      - "8000:8000"
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'tododb'
      MYSQL_USER: 'todouser'
      MYSQL_PASSWORD: 'todopass'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: