services:
  todoapp:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopass
    depends_on:
      - db
  
  db:
    image: postgres:16-alpine
    ports: 
      - 5432:5432 
    environment:
      - POSTGRES_DB=tododb
      - POSTGRES_USER=todouser
      - POSTGRES_PASSWORD=todopass